services:
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true