services:
  db:
    image: postgres:15
    container_name: chat-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_app_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data:
