---
openapi: 3.0.1
info:
  title: Chat API
  version: v1
  description: API documentation for the Chat Application
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    error_object:
      type: object
      properties:
        error:
          type: string
          example: Not Found
        message:
          type: string
          example: Conversation not found
    errors_object:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
          example:
          - Content can't be blank
    conversation_response:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              properties:
                title:
                  type: string
                created_at:
                  type: string
                  format: date-time
                updated_at:
                  type: string
                  format: date-time
    conversations_response:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              attributes:
                type: object
                properties:
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
    message_response:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              properties:
                content:
                  type: string
                role:
                  type: string
                conversation_id:
                  type: integer
                created_at:
                  type: string
                  format: date-time
                updated_at:
                  type: string
                  format: date-time
    messages_response:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              attributes:
                type: object
                properties:
                  content:
                    type: string
                  role:
                    type: string
                  conversation_id:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
paths:
  "/api/v1/conversations":
    get:
      summary: Retrieves all conversations
      tags:
      - Conversations
      responses:
        '200':
          description: conversations found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/conversations_response"
    post:
      summary: Creates a conversation
      tags:
      - Conversations
      parameters: []
      responses:
        '201':
          description: conversation created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation:
                  type: object
                  properties:
                    title:
                      type: string
                      description: Optional title. If blank, will be auto-generated
                        as "Conversation {number}"
  "/api/v1/conversations/{id}":
    get:
      summary: Retrieves a conversation
      tags:
      - Conversations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: conversation found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/conversation_response"
        '404':
          description: conversation not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
    delete:
      summary: Deletes a conversation
      tags:
      - Conversations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: conversation deleted
        '404':
          description: conversation not found
  "/api/v1/conversations/{conversation_id}/messages":
    get:
      summary: Retrieves all messages for a conversation
      tags:
      - Messages
      parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: messages found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/messages_response"
        '404':
          description: conversation not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_object"
    post:
      summary: Creates a message
      tags:
      - Messages
      parameters:
      - name: conversation_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: message created
        '422':
          description: invalid request
        '404':
          description: conversation not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  properties:
                    content:
                      type: string
                  required:
                  - content
              required:
              - message
